#! /bin/bash

####################################################################################################
#
# Setup source for UNIX
#
#   Must be run after a fresh git clone to generate some files
#
#   Must be executed from source directory
#
####################################################################################################

rule='--------------------------------------------------------------------------------'

####################################################################################################

# Fixme: use inv qt.rcc

echo
echo $rule
echo Generate image-browser.rcc and ImageBrowserRessource.py
echo

pushd rcc # move to

# make # same as
# rcc-qt5 -binary image-browser.qrc -o image-browser.rcc
# pyrcc5 -o ImageBrowserRessource.py image-browser.qrc
pyside6-rcc -o ImageBrowserRessource.py image-browser.qrc

popd # go back

echo
ls -l share/*{.rcc,ce.py}

####################################################################################################

echo
echo $rule
echo Generate .qm translations files
echo

./tools/translate --release

echo
ls -l share/translations/*.qm
